// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
//  // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBi6J8l4NRI5K7sbtq98o_opkgqZgpXqw',
    appId: '1:858923046574:web:a296cd59ee10cdf4a5bf3f',
    messagingSenderId: '858923046574',
    projectId: 'ooriba-s3-add23',
    authDomain: 'ooriba-s3-add23.firebaseapp.com',
    storageBucket: 'ooriba-s3-add23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4N81eMy4UBlX5v-LoKJAv6awqVH5kc9Q',
    appId: '1:858923046574:android:fe43cc72038e518ea5bf3f',
    messagingSenderId: '858923046574',
    projectId: 'ooriba-s3-add23',
    storageBucket: 'ooriba-s3-add23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrjCHjq333uT-OBCLAsLw07xRvT3ivCa4',
    appId: '1:858923046574:ios:d08ec8149823fd49a5bf3f',
    messagingSenderId: '858923046574',
    projectId: 'ooriba-s3-add23',
    storageBucket: 'ooriba-s3-add23.appspot.com',
    iosBundleId: 'com.example.ooribaS3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrjCHjq333uT-OBCLAsLw07xRvT3ivCa4',
    appId: '1:858923046574:ios:d08ec8149823fd49a5bf3f',
    messagingSenderId: '858923046574',
    projectId: 'ooriba-s3-add23',
    storageBucket: 'ooriba-s3-add23.appspot.com',
    iosBundleId: 'com.example.ooribaS3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBi6J8l4NRI5K7sbtq98o_opkgqZgpXqw',
    appId: '1:858923046574:web:d8641907841987f5a5bf3f',
    messagingSenderId: '858923046574',
    projectId: 'ooriba-s3-add23',
    authDomain: 'ooriba-s3-add23.firebaseapp.com',
    storageBucket: 'ooriba-s3-add23.appspot.com',
  );
}
